//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketLand_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.booking_detail = new HashSet<booking_detail>();
        }
    
        public int booking_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public Nullable<int> booking_status { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public string total_price { get; set; }
    
        public virtual member member { get; set; }
        public virtual schedule schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_detail> booking_detail { get; set; }
    }
}
