//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketLand_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> movie_id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
        public Nullable<double> comment_star { get; set; }
    
        public virtual member member { get; set; }
        public virtual movy movy { get; set; }
    }
}
