//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketLand_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int event_id { get; set; }
        public Nullable<int> movie_id { get; set; }
        public string event_name { get; set; }
        public string event_description { get; set; }
        public Nullable<System.DateTime> event_date_start { get; set; }
        public Nullable<System.DateTime> event_time_end { get; set; }
        public string event_image { get; set; }
    
        public virtual movy movy { get; set; }
    }
}
