//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketLand_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movy()
        {
            this.comments = new HashSet<comment>();
            this.news = new HashSet<news>();
            this.schedules = new HashSet<schedule>();
        }
    
        public int movie_id { get; set; }
        public string movie_name { get; set; }
        public string movie_description { get; set; }
        public string movie_trailer { get; set; }
        public string movie_cens { get; set; }
        public string movie_genres { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> movie_release { get; set; }
        public Nullable<System.TimeSpan> movie_duration { get; set; }
        public string movie_format { get; set; }
        public string movie_poster { get; set; }
        public string movie_actor { get; set; }
        public string movie_director { get; set; }
        public Nullable<int> movie_status { get; set; }
        public Nullable<double> rate { get; set; }
        public string movie_banner { get; set; }


        public int DurationInMinutes { get; set; }
        public int numberMoviesEnable { get; set; }
        public int numberMoviesDisable { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news> news { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schedule> schedules { get; set; }
    }
}
