//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketLand_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seat()
        {
            this.booking_detail = new HashSet<booking_detail>();
        }
    
        public int seat_id { get; set; }
        public string seat_type { get; set; }
        public Nullable<int> room_id { get; set; }
        public string row { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<bool> seats_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_detail> booking_detail { get; set; }
        public virtual room room { get; set; }
    }
}
